---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-syslog-config
  namespace: observability
data:
  vector.yaml: |-
    # Vector Configuration for Syslog Collection
    data_dir: /vector-data-dir

    # Sources - Syslog inputs
    sources:
      cisco_syslog_udp:
        type: syslog
        address: "0.0.0.0:514"
        mode: udp
        max_length: 102400
        host_key: "syslog_host"

      unifi_syslog_udp:
        type: syslog
        address: "0.0.0.0:5514"
        mode: udp
        max_length: 102400
        host_key: "syslog_host"

      cisco_syslog_tcp:
        type: syslog
        address: "0.0.0.0:1514"
        mode: tcp
        max_length: 102400
        host_key: "syslog_host"

      unifi_syslog_tcp:
        type: syslog
        address: "0.0.0.0:6514"
        mode: tcp
        max_length: 102400
        host_key: "syslog_host"

    # Transforms - Add metadata
    transforms:
      add_cisco_metadata:
        type: remap
        inputs:
          - cisco_syslog_udp
          - cisco_syslog_tcp
        source: |
          .device_type = "cisco"
          .log_source = "network_device"

      add_unifi_metadata:
        type: remap
        inputs:
          - unifi_syslog_udp
          - unifi_syslog_tcp
        source: |
          .device_type = "unifi"
          .log_source = "network_device"

    # Sinks - Output to Victoria Logs
    sinks:
      victoria_logs:
        type: http
        inputs:
          - add_cisco_metadata
          - add_unifi_metadata
        uri: "http://victoria-logs-server.observability.svc.cluster.local:9428/insert/jsonline"
        method: post
        encoding:
          codec: json
        batch:
          max_bytes: 1048576
          timeout_secs: 5
        request:
          headers:
            Content-Type: "application/x-ndjson"

      # Debug output to stdout
      debug_stdout:
        type: console
        inputs:
          - add_cisco_metadata
          - add_unifi_metadata
        encoding:
          codec: json
        target: stdout

    # API for health checks
    api:
      enabled: true
      address: "0.0.0.0:8686"
