---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/cilium.io/ciliumenvoyconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: rook-ceph-dashboard-retries
  namespace: rook-ceph
spec:
  resources:
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      # Cilium names the RouteConfiguration for an HTTPRoute as: httproute/<ns>/<name>
      name: httproute/rook-ceph/rook-ceph-dashboard
      virtual_hosts:
        # And the vhost as: vhost-httproute/<ns>/<name>
        - name: vhost-httproute/rook-ceph/rook-ceph-dashboard
          retry_policy:
            retry_on: "5xx,connect-failure,refused-stream,reset,disconnect,isolated_failure"
            num_retries: 3
            per_try_timeout: 2s
