---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          coredns:
            image:
              repository: mirror.gcr.io/coredns/coredns
              tag: 1.12.4
            args:
              - -conf
              - /etc/coredns/Corefile
            restartPolicy: Always
          gluetun:
            dependsOn:
              - coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00 # yamllint disable-line rule:line-length
            env:
              DOT: "off"
              DNS_ADDRESS: 127.0.0.2
              # yamllint disable-line rule:line-length
              HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: &gluetunAuthPath /gluetun/auth.toml
              # yamllint disable-line rule:line-length
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16 # Allow access to k8s subnets
              HEALTH_SERVER_ADDRESS: :9999
              HEALTH_SUCCESS_WAIT_DURATION: 60s
              VPN_TYPE: openvpn
              OPENVPN_CUSTOM_CONFIG: &gluetunOpenvpnPath /gluetun/custom.conf
              VPN_INTERFACE: tun0
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec: &probe
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      # yamllint disable-line rule:line-length
                      - |
                        url="http://localhost:8000/v1/openvpn/status"
                        status=$(wget -qO- --timeout=5 \
                          --header="X-API-KEY:$GLUETUN_CONTROL_SERVER_API_KEY" \
                          $url 2>/dev/null | grep -o '"status":"[^"]*"' | \
                          cut -d'"' -f4)
                        if [ "$status" = "running" ]; then
                          exit 0
                        else
                          echo "OpenVPN status: $status"
                          exit 1
                        fi
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
                  failureThreshold: 30
              startup:
                enabled: true
                custom: true
                spec:
                  <<: *probe
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    # yamllint disable-line rule:line-length
                    - >-
                      (ip rule del table 51820;
                       ip -6 rule del table 51820) || true
            restartPolicy: Always
            securityContext:
              # can't be non-root, or it has no access to tunnel
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false # wants to create a user, etc
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              limits:
                squat.ai/tun: 1
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524 # yamllint disable-line rule:line-length
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 80
              PUSHOVER_ENABLED: true
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                memory: 10Gi
          vuetorrent:
            dependsOn: app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.5.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        primary: true
        forceRename: *app
        ports:
          http:
            primary: true
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    configMaps:
      config:
        forceRename: &configMapName "{{ .Release.Name }}-configmap"
        data:
          .qbt.toml: |-
            [qbittorrent]
            addr = "http://localhost:80"
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      config-file:
        type: configMap
        name: *configMapName
        globalMounts:
          - path: /config/.qbt.toml
            subPath: .qbt.toml
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          qbittorrent:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
                readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            app:
              - path: /addons
                subPath: addons
            vuetorrent:
              - path: /addons
                subPath: addons
      gluetun-auth:
        type: secret
        name: "{{ .Release.Name }}-gluetun"
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: *gluetunAuthPath
                subPath: auth.toml
      gluetun-openvpn:
        type: secret
        name: qbittorrent-secret
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: *gluetunOpenvpnPath
                subPath: openvpn_config
      media:
        type: nfs
        server: nas01.${SECRET_DOMAIN}
        path: /mnt/flashstor/data
        globalMounts:
          - path: /media/torrents
            subPath: torrents
      qbrr:
        type: image
        image: ghcr.io/buroa/qbrr:0.1.1@sha256:fe4a1d100ba896999253a5122d9c77cc4920779d618c23f765458cb6ec7383ca # yamllint disable-line rule:line-length
      tmp:
        type: emptyDir
