---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmsingle-stack
spec:
  selector:
    matchLabels:
      app.vm.single-node: vmsingle-stack
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmagent-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmagent
      app.kubernetes.io/instance: stack
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalert-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmalert
      app.kubernetes.io/instance: stack
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: vmalert-stack
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalertmanager-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmalertmanager
      app.kubernetes.io/instance: stack
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: victoria-metrics-operator
