[pre-commit]
parallel = true

[pre-commit.commands.format-yaml]
run = "yamlfmt {staged_files}"
glob = ["*.yaml", "*.yml"]
exclude = ["*.sops.yaml"]
stage_fixed = true

[pre-commit.commands.go-fmt]
run = "gofmt -l -w {staged_files} && go mod tidy"
root = "cmd/homeops-cli/"
glob = ["*.go"]
stage_fixed = true

[pre-commit.commands.go-lint]
run = """
if command -v golangci-lint >/dev/null 2>&1; then
    golangci-lint run --fix ./...
else
    echo "⚠️  golangci-lint not found, running go vet instead"
    go vet ./...
fi
"""
root = "cmd/homeops-cli/"
glob = ["*.go"]
stage_fixed = true