---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: "0.14.6"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"

    storageClasses:
      - name: truenas-iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: truenas-iscsi-snapshot
        parameters:
        secrets:
          snapshotter-secret:

    controller:
      enabled: true
      strategy: node
      externalAttacher:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 128Mi
      externalProvisioner:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 128Mi
      externalResizer:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 128Mi
      externalSnapshotter:
        enabled: true
        image: registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 128Mi
      driver:
        image: democraticcsi/democratic-csi:v1.9.3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 256Mi
        logLevel: info

    node:
      driver:
        image: democraticcsi/democratic-csi:v1.9.3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 256Mi
        logLevel: info
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.120.10
          port: 80
          apiKey: "op://Infrastructure/democratic-csi/TRUENAS_APIKEY"
          username: root
        zfs:
          datasetParentName: flashstor/kubernetes/volumes
          detachedSnapshotsDatasetParentName: flashstor/kubernetes/snapshots
          zvolBlocksize:
          zvolCompression:
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: "192.168.120.10:3260"
          targetPortals:
            - "192.168.120.10:3260"
            - "192.168.120.4:3260"
          interface:
          namePrefix: csi-
          nameSuffix: ""
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0
