machine:
  type: controlplane
  network:
    hostname: k8s-0
    interfaces:
      - deviceSelector:
          hardwareAddr: 00:a0:98:28:c8:83
        mtu: 9000
        dhcp: true
        vip:
          ip: 192.168.120.100
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: "!system_disk"
  minSize: 1024GB
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m