---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    storageClass:
      create: true
      name: nfs-slow
      parameters:
        server: 192.168.120.10
        share: /mnt/flashstor/kubernetes
      mountOptions:
        - nfsvers=4.2
        - nconnect=16
        - hard
        - noatime
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
