---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./replicationdestination.yaml
  # - ./replicationsource.yaml  # Disabled: v2 doesn't support snapshot-based backups, using Longhorn S3 backups instead
