---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/operator.victoriametrics.com/vmpodsscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: flux-controllers
  namespace: flux-system
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - kustomize-controller
          - source-controller
          - notification-controller
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
