---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
  endpoints:
    - port: http
      path: /metrics
