---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-agent
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-operator
spec:
  selector:
    matchLabels:
      name: cilium-operator
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
