---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  external:
    adminPassword:
      name: grafana-admin-secret
      key: GF_SECURITY_ADMIN_PASSWORD
    adminUser:
      name: grafana-admin-secret
      key: GF_SECURITY_ADMIN_USER
  preferences:
    allowCrossNamespaceImport: true
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_DATE_FORMATS_USE_BROWSER_LOCALE
                  value: "true"
                - name: GF_EXPLORE_ENABLED
                  value: "true"
                - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
                  value: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel
                - name: GF_SECURITY_ANGULAR_SUPPORT_ENABLED
                  value: "true"
                - name: GF_SERVER_ROOT_URL
                  value: https://grafana.${SECRET_DOMAIN}
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    auth.anonymous:
      enabled: "true"
      org_id: "1"
      org_name: Main Org.
      org_role: Viewer
    log:
      mode: console
    news:
      news_feed_enabled: "false"
