---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./grafanadatasource.yaml
  - ./httproute.yaml
  - ./sidecar-provider.yaml
  - ./dashboards/cert-manager.yaml
  - ./dashboards/ceph.yaml
  - ./dashboards/cloudflared.yaml
  - ./dashboards/envoy.yaml
  - ./dashboards/external-dns.yaml
  - ./dashboards/kubernetes.yaml
  - ./dashboards/misc.yaml
  - ./dashboards/node-exporters.yaml
  - ./dashboards/unifi.yaml
