---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  labels:
    grafana_dashboard: "1"
data:
  provider.yaml: |-
    apiVersion: 1
    providers:
      - name: sidecar
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        allowUiUpdates: true
        updateIntervalSeconds: 30
        foldersFromFilesStructure: true
        options:
          path: /var/lib/grafana/dashboards/sidecar
