---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: autobrr-logs
  namespace: observability
  labels:
    rule-type: vlogs
spec:
  groups:
    - name: autobrr-logs
      type: vlogs
      interval: 1m
      rules:
        - alert: AutobrrDatabaseIsLocked
          expr: |
            {app="autobrr"} | regexp "(?i)database is locked" | stats count() errors | filter errors:>0
          for: 5m
          annotations:
            summary: Autobrr is experiencing database lock issues
            description: "Autobrr has encountered {{ $value }} database lock errors in the last 5 minutes"
          labels:
            severity: critical
            app: autobrr

        - alert: AutobrrDatabaseIsMalformed
          expr: |
            {app="autobrr"} | regexp "(?i)database image malformed" | stats count() errors | filter errors:>0
          for: 5m
          annotations:
            summary: Autobrr is experiencing database issues
            description: "Autobrr has encountered {{ $value }} database corruption errors in the last 5 minutes"
          labels:
            severity: critical
            app: autobrr
