---
groups:
  - name: radarr-logs
    type: vlogs
    interval: 1m
    rules:
      - alert: RadarrDatabaseIsLocked
        expr: |
          {app="radarr"} | regexp "(?i)database is locked" | stats count() errors | filter errors:>0
        for: 5m
        annotations:
          summary: Radarr is experiencing database lock issues
          description: "Radarr has encountered database lock errors in the last 5 minutes"
        labels:
          severity: critical
          app: radarr

      - alert: RadarrDatabaseIsMalformed
        expr: |
          {app="radarr"} | regexp "(?i)database disk image is malformed" | stats count() errors | filter errors:>0
        for: 5m
        annotations:
          summary: Radarr database is corrupted
          description: "Radarr has encountered database corruption errors in the last 5 minutes"
        labels:
          severity: critical
          app: radarr
