---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 1h
  provider: generic
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    semver: ">=5.0.0 <6.0.0"
