---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    persistence:
      defaultDataLocality: best-effort
    defaultSettings:
      defaultDataPath: "/var/mnt/longhorn"
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: 5
      storageReservedPercentageForDefaultDisk: 10
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      replicaAutoBalance: true
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20

    ingress:
      enabled: false

    metrics:
      serviceMonitor:
        enabled: true
