---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 3
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn
      defaultReplicaCount: 3
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      restoreVolumeRecurringJobs: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      v1DataEngine: false
      v2DataEngine: true
      dataEngine: v2
    ingress:
      enabled: false
