---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/install
        value:
          remediation:
            retries: -1
      - op: add
        path: /spec/upgrade
        value:
          cleanupOnFail: true
          remediation:
            retries: 3
      - op: add
        path: /spec/install/crds
        value: CreateReplace
      - op: add
        path: /spec/upgrade/crds
        value: CreateReplace
