---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: irc-keepalive-script
    files:
      - keepalive.py=./resources/keepalive.py
generatorOptions:
  disableNameSuffixHash: true
