---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-crds
spec:
  interval: 5m
  ref:
    tag: 1.5.1
  url: oci://docker.io/envoyproxy/gateway-helm
