---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-logs-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-logs-single
      app.kubernetes.io/instance: victoria-logs
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: victoria-logs-server
