---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  patches:
    - # Enable Sops decryption on all child Kustomizations
      target:
        kind: Kustomization
        version: v1
        group: kustomize.toolkit.fluxcd.io
      patch: |-
        - op: add
          path: /spec/decryption
          value:
            provider: sops
    - # Add common-config component to all child Kustomizations
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-config-secret
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: "substitution.flux.home.arpa/disabled!=true"
