---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/alerts
  - ../../components/cluster-secret

resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./keda/ks.yaml
  - ./kromgo/ks.yaml
  - ./victoria-metrics/ks.yaml
  - ./vector-syslog/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./silence-operator/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./unpoller/ks.yaml
