---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-toolkit-flux-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gateway
  interval: 10m
  path: "./kubernetes/apps/longhorn-system/longhorn/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      GATEWAY_IP: "192.168.123.130"
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: cert-manager
      namespace: cert-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-toolkit-flux-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-storageclass
  namespace: &namespace longhorn-system
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: longhorn-storageclass
  interval: 10m
  path: "./kubernetes/apps/longhorn-system/longhorn/storageclass"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: longhorn
      namespace: *namespace
