---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./envoy.yaml
  - ./grafanadashboard.yaml
  - ./observability.yaml
  # - ./vmobservability.yaml  # Temporarily disabled until VictoriaMetrics CRDs are installed
