---
# yaml-language-server: $schema=https://kubernetes-schema.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit-syslog
spec:
  chartRef:
    kind: OCIRepository
    name: fluent-bit-syslog
  interval: 1h
  values:
    kind: Deployment
    replicaCount: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - fluent-bit-syslog
              topologyKey: kubernetes.io/hostname
    nameOverride: fluent-bit-syslog
    fullnameOverride: fluent-bit-syslog
    service:
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: "192.168.120.101"
    extraPorts:
      - port: 514
        containerPort: 514
        protocol: UDP
        name: syslog-udp
      - port: 514
        containerPort: 5140
        protocol: TCP
        name: syslog-tcp
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    config:
      service: |-
        [SERVICE]
          daemon off
          flush 5
          log_level debug
          parsers_file /fluent-bit/etc/parsers.conf
          parsers_file /fluent-bit/etc/conf/custom_parsers.conf
          http_server on
          http_listen 0.0.0.0
          http_port 2020
          health_check on

      inputs: |-
        [INPUT]
          name udp
          alias syslog-udp
          listen 0.0.0.0
          port 514
          tag network.syslog
          format none
          chunk_size 64k
          buffer_size 256k

        [INPUT]
          name tcp
          alias syslog-tcp
          listen 0.0.0.0
          port 5140
          tag network.syslog.tcp
          format none
          chunk_size 64k
          buffer_size 256k

      filters: |-
        [FILTER]
          name parser
          match network.*
          key_name log
          parser syslog-rfc3164
          parser syslog-rfc5424
          preserve_key on
          reserve_data on

        [FILTER]
          name parser
          match network.*
          key_name message
          parser custom-unifi-message
          parser custom-cisco-message
          parser custom-cef
          preserve_key on
          reserve_data on

        [FILTER]
          name record_modifier
          match network.*
          record log_source network_device
          record cluster home-ops
          record log_type syslog

      customParsers: |-
        [PARSER]
          name custom-unifi-message
          format regex
          regex /^(?<process>[a-zA-Z0-9_\-]+)(?:\[(?<pid>[0-9]+)\])?: *(?<log_message>.*)$/

        [PARSER]
          name custom-cisco-message
          format regex
          regex /^%(?<facility>[A-Z0-9_]+)-(?<severity>[0-7])-(?<mnemonic>[A-Z0-9_]+): *(?<log_message>.*)$/

        [PARSER]
          name custom-cef
          format regex
          regex /^CEF:(?<cef_version>\d+)\|(?<device_vendor>[^|]*)\|(?<device_product>[^|]*)\|(?<device_version>[^|]*)\|(?<signature_id>[^|]*)\|(?<name>[^|]*)\|(?<severity>[^|]*)\|(?<extension>.*)$/

      outputs: |-
        [OUTPUT]
          name http
          match network.*
          host victoria-logs-server.observability.svc.cluster.local
          port 9428
          uri /insert/jsonline?_stream_fields=source_host,ident,host,log_source,process,facility&_msg_field=message&_time_field=date
          format json_lines
          json_date_format iso8601
          compress gzip
          retry_limit 3

    dashboards:
      enabled: true
      annotations:
        grafana_folder: observability

    serviceMonitor:
      enabled: true
      interval: 30s
