---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: flux-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
  endpoints:
    - port: http-prom
      path: /metrics
      honorLabels: true
