---
# Source: Inferred from parent Kustomization namespace
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
      fieldPaths:
        - spec.targetNamespace
      options:
        create: true
