---
# ServiceMonitor for scraping CSI plugin liveness metrics
# This allows VictoriaMetrics (via Prometheus converter) to scrape CSI metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: rook-ceph
  labels:
    app.kubernetes.io/part-of: rook-ceph
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: csi-http-metrics
      path: /metrics
      interval: 30s
